### ISSUE TITLE
Problems check doesn't work

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#33]
I have created a problem and added tests for it. After I am trying to submit my solution and see error 500 after sending it. Here is a part of the log where it is shown:
```
Completed 200 OK in 92ms (Views: 24.3ms | ActiveRecord: 2.3ms)
Started POST "/solutions" for 141.101.81.100 at 2015-05-04 16:04:48 +0300
Processing by SolutionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"c02BjOhftQVkEQggSnnEiffBAcY5FRnHoe4wcRPYvUM=", "solution"=>{"problem_id"=>"1", "contest_id"=>"4", "source"=>#<ActionDispatch::Http::Upload$
[paperclip] Saving attachments.
Completed 500 Internal Server Error in 73ms

NoMethodError (undefined method `strip' for nil:NilClass):
  app/models/repo.rb:71:in `block in configuration'
  app/models/repo.rb:89:in `inside'
  app/models/repo.rb:70:in `configuration'
  app/models/repo.rb:28:in `ready?'
  app/models/repo.rb:24:in `prepare'
  app/models/repo.rb:43:in `block in commit'
  app/models/repo.rb:94:in `block in inside'
  app/models/repo.rb:91:in `inside'
  app/models/repo.rb:42:in `commit'
  app/models/solution.rb:48:in `log'
  app/controllers/solutions_controller.rb:66:in `block in create'
  app/controllers/solutions_controller.rb:141:in `block in creating'
  app/controllers/solutions_controller.rb:140:in `creating'
  app/controllers/solutions_controller.rb:64:in `create'
```

**Comment by alexbagirov** [comment]
There is also a problem with sending emails. From log:
```
Started POST "/password_resets" for 141.101.81.100 at 2015-05-04 16:11:41 +0300
Processing by PasswordResetsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"c02BjOhftQVkEQggSnnEiffBAcY5FRnHoe4wcRPYvUM=", "email"=>"", "commit"=>"Send"}
  Rendered password_resets/new.html.haml within layouts/application (1.1ms)
Completed 200 OK in 8ms (Views: 5.4ms | ActiveRecord: 0.5ms)
Started POST "/password_resets" for 141.101.81.100 at 2015-05-04 16:12:04 +0300
Processing by PasswordResetsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"c02BjOhftQVkEQggSnnEiffBAcY5FRnHoe4wcRPYvUM=", "email"=>"alexfox@protonmail.ch", "commit"=>"Send"}
  Rendered notifier/password_reset_instructions.mn.text.erb (0.6ms)

Sent mail to alexfox@protonmail.ch (66ms)
Completed 500 Internal Server Error in 314ms

Errno::ECONNREFUSED (Connection refused - connect(2)):
  app/controllers/password_resets_controller.rb:12:in `create'
```

**Comment by alexbagirov** [comment]
And that is an error log for searching:
```
Started GET "/search?q=A+new+contest+is+announced%21" for 141.101.81.100 at 2015-05-04 16:06:15 +0300
Processing by SearchController#index as HTML
  Parameters: {"q"=>"A new contest is announced!"}
Completed 500 Internal Server Error in 1ms

Mysql2::Error (Can't connect to MySQL server on '127.0.0.1' (111)):
  app/controllers/search_controller.rb:9:in `index'
```

As we can see the problem is in database. Is there a way to check the connection?

**Comment by ochko** [comment]
First error occurs because incorrect git path in `config/binaries.yml`. 

Second error occurs due to incorrect smtp settings in `config/mail.yml`.

Last error occurred because there was no mysql server running. Prudge uses postgresql, but sphinx search depends on mysql.

**Comment by alexbagirov** [comment]
> git path

How can I find it? I tried different ways but all of them failed.

> incorrect smtp settings

Ok, will look into it.

> no mysql server running

Also the sphinx is not running. Do I have to configure it for working somehow or just start?

**Comment by alexbagirov** [comment]
Ok, currently git path seems to be fixed and it uploads solutions to the server. After I try to check it and it does nothing (just writing to wait a little and nothing else). 
I tried to start workers but it was always telling me that `rack` and other gems are missing and prompting to run `bundle install`. I did it and tried to run workers again. Now I get this error:
```
administrator@sw-c246:/home/prudge/prudge$ RAILS_ENV=production QUEUE=* bundle exec rake resque:work
rake aborted!
FATAL:  Peer authentication failed for user "prudge"
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1216:in `initialize'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1216:in `new'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1216:in `connect'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:324:in `initialize'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `new'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `postgresql_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/model_schema.rb:308:in `clear_cache!'
/var/lib/gems/1.9.1/gems/activerecord-3.2.13/lib/active_record/railtie.rb:104:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:418:in `_run__1382469174367952652__prepare__3083579769118939652__callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/var/lib/gems/1.9.1/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/prudge/prudge/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-3.2.13/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => resque:work => resque:preload => resque:setup => environment
(See full trace by running task with --trace)
```

**Comment by ochko** [comment]
Probably that's because rbenv isn't configured for `administrator` user. Try running the worker as a `prudge` user.

**Comment by alexbagirov** [comment]
Doesn't work :(
Can you help me, please?

**Comment by alexbagirov** [comment]
It says something like this 
```
rake aborted!
Permission denied - tmp/pids/resque.pid
/var/lib/gems/1.9.1/gems/resque-1.24.1/lib/resque/tasks.rb:36:in `initialize'
/var/lib/gems/1.9.1/gems/resque-1.24.1/lib/resque/tasks.rb:36:in `open'
/var/lib/gems/1.9.1/gems/resque-1.24.1/lib/resque/tasks.rb:36:in `block (2 levels)$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'                /var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'             /var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_cha$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 leve$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_thre$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'  /var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exce$/var/lib/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => resque:work
(See full trace by running task with --trace)
```

**Comment by alexbagirov** [comment]
@ochko, can you help me please?

**Comment by ochko** [comment]
I am doing some work at https://github.com/ochko/prudge/tree/deploy_script branch. This will make installations easier.

**Comment by alexbagirov** [comment]
So I have looked through it. It seems to be really helpful because it configures the system by itself so nobody can make any mistake :smile:
